controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    use_sim_time: true

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_state_broadcaster:
  ros__parameters:
    publish_rate: 1000.0

joint_trajectory_controller:
  ros__parameters:
    state_publish_rate: 1000.0 # Defaults to 50
    action_monitor_rate: 1000.0 # Defaults to 20
    joints:
      - fr1_joint
      - fr2_joint
      - fr3_joint
      - fl1_joint
      - fl2_joint
      - fl3_joint
      - rr1_joint
      - rr2_joint
      - rr3_joint
      - rl1_joint
      - rl2_joint
      - rl3_joint
      #- lleg1_ax1_joint
      #- lleg1_ax2_joint
      #- lleg1_ax3_joint
      #- lleg2_ax1_joint
      #- lleg2_ax2_joint
      #- lleg2_ax3_joint
      #- rleg1_ax1_joint
      #- rleg1_ax2_joint
      #- rleg1_ax3_joint
      #- rleg2_ax1_joint
      #- rleg2_ax2_joint
      #- rleg2_ax3_joint
      
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position

    allow_partial_joints_goal: false 
    open_loop_control: false
    allow_integration_in_goal_trajectories: false
    constraints:
      stopped_velocity_tolerance: 0.0 
      goal_time: 0.0  
    gains:
        fr1_joint  : {p: 100, i: 10, d: 5, i_clamp_min:  -1000, i_clamp_max: 1000}
        fr2_joint  : {p: 100, i: 10, d: 5, i_clamp_min:  -1000, i_clamp_max: 1000}
        fr3_joint  : {p: 100, i: 10, d: 5, i_clamp_min:  -1000, i_clamp_max: 1000}

        fl1_joint  : {p: 100, i: 10, d: 5, i_clamp_min:  -1000, i_clamp_max: 1000}
        fl2_joint  : {p: 100, i: 10, d: 5, i_clamp_min:  -1000, i_clamp_max: 1000}
        fl3_joint  : {p: 100, i: 10, d: 5, i_clamp_min:  -1000, i_clamp_max: 1000}

        rr1_joint  : {p: 100, i: 10, d: 5, i_clamp_min:  -1000, i_clamp_max: 1000}
        rr2_joint  : {p: 100, i: 10, d: 5, i_clamp_min:  -1000, i_clamp_max: 1000}
        rr3_joint  : {p: 100, i: 10, d: 5, i_clamp_min:  -1000, i_clamp_max: 1000}

        rl1_joint  : {p: 100, i: 10, d: 5, i_clamp_min:  -1000, i_clamp_max: 1000}
        rl2_joint  : {p: 100, i: 10, d: 5, i_clamp_min:  -1000, i_clamp_max: 1000}
        rl3_joint  : {p: 100, i: 10, d: 5, i_clamp_min:  -1000, i_clamp_max: 1000}
